// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrlC-9dJlSNHtw1xDGqdHr9_olDY6lW0U',
    appId: '1:479518471903:web:b1479e7711e5440b559b6a',
    messagingSenderId: '479518471903',
    projectId: 'resume-app-omer',
    authDomain: 'resume-app-omer.firebaseapp.com',
    storageBucket: 'resume-app-omer.firebasestorage.app',
    measurementId: 'G-M4RX0HVK3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXKKsorn6tXiWbpgt4wQstz1KxlANDMoY',
    appId: '1:479518471903:android:8828367d725570e8559b6a',
    messagingSenderId: '479518471903',
    projectId: 'resume-app-omer',
    storageBucket: 'resume-app-omer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7ZNNEhisPd1hhAgiRzpE2lJOrc2RT_R8',
    appId: '1:479518471903:ios:4d8779e977822510559b6a',
    messagingSenderId: '479518471903',
    projectId: 'resume-app-omer',
    storageBucket: 'resume-app-omer.firebasestorage.app',
    iosBundleId: 'com.psychobooper.resumeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7ZNNEhisPd1hhAgiRzpE2lJOrc2RT_R8',
    appId: '1:479518471903:ios:4d8779e977822510559b6a',
    messagingSenderId: '479518471903',
    projectId: 'resume-app-omer',
    storageBucket: 'resume-app-omer.firebasestorage.app',
    iosBundleId: 'com.psychobooper.resumeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrlC-9dJlSNHtw1xDGqdHr9_olDY6lW0U',
    appId: '1:479518471903:web:7aaab98761b45153559b6a',
    messagingSenderId: '479518471903',
    projectId: 'resume-app-omer',
    authDomain: 'resume-app-omer.firebaseapp.com',
    storageBucket: 'resume-app-omer.firebasestorage.app',
    measurementId: 'G-S20DFSXJRK',
  );
}
