name: Deploy Flutter Web to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1 - Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️ - Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"

      # 3️ - Build for Web (release)
      - name: Build Flutter Web
        run: flutter build web --release

      # 4️ - Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          channelId: live
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: "resume-app-omer"